---
title: "Animation Gallery"
subtitle: "All animations from Animate.css"
format: revealjs
filters:
  - more-fragments
---

## About These Animations

All animations in this extension come from [Animate.css](https://animate.style/), a library of ready-to-use, cross-browser animations.

::: {.fragment .fadeIn}
Navigate with arrow keys to see each animation.
:::

::: {.fragment .fadeIn}
Press **left arrow** to see reverse animations!
:::

## Attention Seekers

:::: {.columns}
::: {.column width="33%"}
::: {.fragment .bounce}
bounce
:::

::: {.fragment .flash}
flash
:::

::: {.fragment .pulse}
pulse
:::

::: {.fragment .rubberBand}
rubberBand
:::
:::

::: {.column width="33%"}
::: {.fragment .shakeX}
shakeX
:::

::: {.fragment .shakeY}
shakeY
:::

::: {.fragment .headShake}
headShake
:::

::: {.fragment .swing}
swing
:::
:::

::: {.column width="33%"}
::: {.fragment .tada}
tada
:::

::: {.fragment .wobble}
wobble
:::

::: {.fragment .jello}
jello
:::

::: {.fragment .heartBeat}
heartBeat
:::
:::
::::

## Back Animations

:::: {.columns}
::: {.column width="50%"}
**Entrances**

::: {.fragment .backInDown}
backInDown
:::

::: {.fragment .backInLeft}
backInLeft
:::

::: {.fragment .backInRight}
backInRight
:::

::: {.fragment .backInUp}
backInUp
:::
:::

::: {.column width="50%"}
**Exits**

::: {.fragment .backOutDown}
backOutDown
:::

::: {.fragment .backOutLeft}
backOutLeft
:::

::: {.fragment .backOutRight}
backOutRight
:::

::: {.fragment .backOutUp}
backOutUp
:::
:::
::::

## Bouncing Animations

:::: {.columns}
::: {.column width="50%"}
**Entrances**

::: {.fragment .bounceIn}
bounceIn
:::

::: {.fragment .bounceInDown}
bounceInDown
:::

::: {.fragment .bounceInLeft}
bounceInLeft
:::

::: {.fragment .bounceInRight}
bounceInRight
:::

::: {.fragment .bounceInUp}
bounceInUp
:::
:::

::: {.column width="50%"}
**Exits**

::: {.fragment .bounceOut}
bounceOut
:::

::: {.fragment .bounceOutDown}
bounceOutDown
:::

::: {.fragment .bounceOutLeft}
bounceOutLeft
:::

::: {.fragment .bounceOutRight}
bounceOutRight
:::

::: {.fragment .bounceOutUp}
bounceOutUp
:::
:::
::::

## Fading Entrances

:::: {.columns}
::: {.column width="33%"}
::: {.fragment .fadeIn}
fadeIn
:::

::: {.fragment .fadeInDown}
fadeInDown
:::

::: {.fragment .fadeInDownBig}
fadeInDownBig
:::

::: {.fragment .fadeInLeft}
fadeInLeft
:::

::: {.fragment .fadeInLeftBig}
fadeInLeftBig
:::
:::

::: {.column width="33%"}
::: {.fragment .fadeInRight}
fadeInRight
:::

::: {.fragment .fadeInRightBig}
fadeInRightBig
:::

::: {.fragment .fadeInUp}
fadeInUp
:::

::: {.fragment .fadeInUpBig}
fadeInUpBig
:::
:::

::: {.column width="33%"}
::: {.fragment .fadeInTopLeft}
fadeInTopLeft
:::

::: {.fragment .fadeInTopRight}
fadeInTopRight
:::

::: {.fragment .fadeInBottomLeft}
fadeInBottomLeft
:::

::: {.fragment .fadeInBottomRight}
fadeInBottomRight
:::
:::
::::

## Fading Exits

:::: {.columns}
::: {.column width="33%"}
::: {.fragment .fadeOut}
fadeOut
:::

::: {.fragment .fadeOutDown}
fadeOutDown
:::

::: {.fragment .fadeOutDownBig}
fadeOutDownBig
:::

::: {.fragment .fadeOutLeft}
fadeOutLeft
:::

::: {.fragment .fadeOutLeftBig}
fadeOutLeftBig
:::
:::

::: {.column width="33%"}
::: {.fragment .fadeOutRight}
fadeOutRight
:::

::: {.fragment .fadeOutRightBig}
fadeOutRightBig
:::

::: {.fragment .fadeOutUp}
fadeOutUp
:::

::: {.fragment .fadeOutUpBig}
fadeOutUpBig
:::
:::

::: {.column width="33%"}
::: {.fragment .fadeOutTopLeft}
fadeOutTopLeft
:::

::: {.fragment .fadeOutTopRight}
fadeOutTopRight
:::

::: {.fragment .fadeOutBottomLeft}
fadeOutBottomLeft
:::

::: {.fragment .fadeOutBottomRight}
fadeOutBottomRight
:::
:::
::::

## Flippers

::: {.fragment .flip}
flip
:::

::: {.fragment .flipInX}
flipInX
:::

::: {.fragment .flipInY}
flipInY
:::

::: {.fragment .flipOutX}
flipOutX
:::

::: {.fragment .flipOutY}
flipOutY
:::

## Lightspeed

::: {.fragment .lightSpeedInRight}
lightSpeedInRight
:::

::: {.fragment .lightSpeedInLeft}
lightSpeedInLeft
:::

::: {.fragment .lightSpeedOutRight}
lightSpeedOutRight
:::

::: {.fragment .lightSpeedOutLeft}
lightSpeedOutLeft
:::

## Rotating Animations

:::: {.columns}
::: {.column width="50%"}
**Entrances**

::: {.fragment .rotateIn}
rotateIn
:::

::: {.fragment .rotateInDownLeft}
rotateInDownLeft
:::

::: {.fragment .rotateInDownRight}
rotateInDownRight
:::

::: {.fragment .rotateInUpLeft}
rotateInUpLeft
:::

::: {.fragment .rotateInUpRight}
rotateInUpRight
:::
:::

::: {.column width="50%"}
**Exits**

::: {.fragment .rotateOut}
rotateOut
:::

::: {.fragment .rotateOutDownLeft}
rotateOutDownLeft
:::

::: {.fragment .rotateOutDownRight}
rotateOutDownRight
:::

::: {.fragment .rotateOutUpLeft}
rotateOutUpLeft
:::

::: {.fragment .rotateOutUpRight}
rotateOutUpRight
:::
:::
::::

## Sliding Animations

:::: {.columns}
::: {.column width="50%"}
**Entrances**

::: {.fragment .slideInDown}
slideInDown
:::

::: {.fragment .slideInLeft}
slideInLeft
:::

::: {.fragment .slideInRight}
slideInRight
:::

::: {.fragment .slideInUp}
slideInUp
:::
:::

::: {.column width="50%"}
**Exits**

::: {.fragment .slideOutDown}
slideOutDown
:::

::: {.fragment .slideOutLeft}
slideOutLeft
:::

::: {.fragment .slideOutRight}
slideOutRight
:::

::: {.fragment .slideOutUp}
slideOutUp
:::
:::
::::

## Zooming Animations

:::: {.columns}
::: {.column width="50%"}
**Entrances**

::: {.fragment .zoomIn}
zoomIn
:::

::: {.fragment .zoomInDown}
zoomInDown
:::

::: {.fragment .zoomInLeft}
zoomInLeft
:::

::: {.fragment .zoomInRight}
zoomInRight
:::

::: {.fragment .zoomInUp}
zoomInUp
:::
:::

::: {.column width="50%"}
**Exits**

::: {.fragment .zoomOut}
zoomOut
:::

::: {.fragment .zoomOutDown}
zoomOutDown
:::

::: {.fragment .zoomOutLeft}
zoomOutLeft
:::

::: {.fragment .zoomOutRight}
zoomOutRight
:::

::: {.fragment .zoomOutUp}
zoomOutUp
:::
:::
::::

## Specials

::: {.fragment .hinge}
hinge
:::

::: {.fragment .jackInTheBox}
jackInTheBox
:::

::: {.fragment .rollIn}
rollIn
:::

::: {.fragment .rollOut}
rollOut
:::
